YOLO_MODEL_PATH = "best.pt"
REID_MODEL_PATH = "model.osnet.pth.tar-10"
INPUT_VIDEO = "15sec_input_720p.mp4"
OUTPUT_VIDEO = "output_reid.mp4"

CONFIDENCE_THRESHOLD = 0.7
IOU_TRACKING_THRESHOLD = 0.5
FEATURE_SIMILARITY_THRESHOLD = 0.4
MAX_LOST_FRAMES = 30
SHORT_LIVED_FRAME_THRESHOLD = 5
PLAYER_CLASS_NAME = 'player'
